version: '3'

services:
  influxdb:
    image: influxdb
    env_file:
      - .env
    container_name: influxdb_mipt
    expose:
      - 8086
    ports:
      - "8086:8086"
  ser-wavelet:
    build: ser-wavelet
    env_file:
      - ser-wavelet/.env
    container_name: ser-wavelet_mipt
