version: '3'

services:
  influxdb:
    image: influxdb:2.7.5
    env_file:
      - .env
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - ./data:/var/lib/influxdb2
      - ./config:/etc/influxdb2

networks:
  my-network:

